version: "3"
services:
  opensearch:
    image: opensearchproject/opensearch:2.4.1
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms4096m -Xmx4096m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ports:
      - 9200:9200
      - 9600:9600
  app:
    image: search-app:1.0
    build: .
    ports:
      - 8080:8080
