FROM opensearchproject/opensearch:2.1.0

RUN /usr/share/opensearch/bin/opensearch-plugin install https://artifacts.opensearch.org/releases/plugins/analysis-kuromoji/2.1.0/analysis-kuromoji-2.1.0.zip
RUN /usr/share/opensearch/bin/opensearch-plugin install https://artifacts.opensearch.org/releases/plugins/analysis-icu/2.1.0/analysis-icu-2.1.0.zip
