info:
  title: title
  version: 1.0.0
openapi: 3.0.2
paths:
  /hello:
    get:
      operationId: hello_hello_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Hello
