[package]
name = "qdrant_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qdrant-client = "0.11.1"
tokio = { version = "1.21.2", features = ["full"] }
tonic = "0.8.2"
