[package]
name = "text_classification_by_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.48"
glob = "0.3.0"
lindera = { version = "0.12.0", features = ["full"] }
linfa = "0.6.0"
linfa-preprocessing = "0.6.0"
ndarray = "0.15.6"
