version: '3'
services:
  app:
    entrypoint: "poetry run uvicorn project_template.api.main:app --host 0.0.0.0 --port 8080"
    volumes:
      - ./model:/opt/ml/project_template/model
    ports:
      - 8080:8080
