version: 1
formatters:
  simple:
    format: '{"created_time":"%(asctime)s", "level":"%(levelname)s", "path":"%(pathname)s", "process_id":"%(process)s", "message":"%(message)s"}'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  simpleExample:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
