[package]
name = "sample_rustml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linfa = "0.6.0"
linfa-datasets = { version = "0.6.0", features = ["winequality"] }
linfa-logistic = "0.6.0"
