[package]
name = "hello_wasm"
version = "0.1.0"
author = ["wararaki718"]
description = "A sample wasm"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
