#ifndef INSTRUCTION_HPP
#define INSTRUCTION_HPP

enum {
    INST_SET_HEALTH = 0x00,
    INST_SET_WISDOM = 0x01,
    INST_SET_AGILITY = 0x02,
    INST_PLAY_SOUND = 0x03,
    INST_SPAWN_PARTICLES = 0x04,
    INST_LITERAL = 0x05
};

#endif // INSTRUCTION_HPP